name: Build Rust image

on:
  workflow_dispatch:
    inputs:
      rustVersion:
        description: 'Rust version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v1.1.1
        with:
          path: cargo-acap-build/
          tags: "${{ github.event.inputs.rustVersion }}"
          build_args: "RUST_VERSION=${{ github.event.inputs.rustVersion }}"
          always_pull: true
          push: true
          add_git_labels: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
